Aidy/create icon in header
SariGlick/TimeOut pull request #101
Opened 2024-07-25 17:55 UTC by aidy8847

2024-07-25 18:27 UTC, ayeletBinder approved these changes

2024-07-29 18:09 UTC, SariGlick requested changes

2024-07-29 18:09 UTC, SariGlick commented on client-side/src/components/iconHeader.jsx
> +        <EmailIcon></EmailIcon>
why do you need this component? you can use @mui/icons-material/Email directly.

2024-07-29 18:09 UTC, SariGlick commented on client-side/src/stories/header/Icon.jsx
> +  const hasMessages = messages.length > 0;
rename to hasUnreadMessages, and count only unread messages

2024-07-29 18:09 UTC, SariGlick commented on client-side/src/stories/header/Icon.jsx
> +  const iconStyle = { color: 'rgb(103, 252, 210)' };
move style to scss file, declare color as variable

2024-07-30 22:23 UTC, SariGlick requested changes

2024-08-03 22:51 UTC, SariGlick requested changes

2024-08-03 22:51 UTC, SariGlick commented on .vscode/settings.json
> +    "window.autoDetectColorScheme": true
I see that adding to gitignore after the file was already added to the PR doesn't remove it,
you have to run git rm --cached .vscode/settings.json
in your vscode's terminal, and then commit & push

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/App.jsx
> -    <>
remove your changes from this file, you can copy its content from main branch in git

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/components/report.jsx
> +import DateInput from "../stories/DateTime/DateInput";
remove this file

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/components/report.scss
> +.start {
remove this file

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/stories/DateTime/DateInput.jsx
> +import PropTypes from 'prop-types';
remove this file

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/stories/DateTime/DateInput.scss
> +
remove this file

2024-08-03 22:51 UTC, SariGlick commented on client-side/src/stories/DateTime/DateInput.stories.js
> +
remove this file

2024-08-03 22:51 UTC, SariGlick commented on .gitignore
> +.vscode/settings.json
please add also package-lock.json

2024-08-05 21:23 UTC, SariGlick approved these changes

2024-08-08 16:05 UTC, e171271 approved these changes

2024-08-08 16:05 UTC, merged