Ayelet/test for client side
SariGlick/TimeOut pull request #106
Opened 2024-07-28 10:56 UTC by ayeletBinder

There are code react - client test.
i installed the jest and react test and i tried it on tow components: popup and loader

2024-07-29 09:24 UTC, lielsa2023 approved these changes

2024-07-29 18:16 UTC, SariGlick requested changes

2024-07-29 18:16 UTC, SariGlick commented on client-side/src/tests/loader.test.js
> +import React from 'react';
tests should be located in client-side/test , and then in the same hierarchy as in the src folder.
as well, adding @testint-library (and jest, if needed) to package.json is missing

2024-07-30 21:01 UTC, SariGlick requested changes

2024-07-30 21:01 UTC, SariGlick commented on client-side/test/loader.test.js
> +import React from 'react';
please place the test file in the same hierarchy as in src folder,
for example this file related to loader, which located in src\stories, so its test should be in test\stories

2024-08-05 22:48 UTC, SariGlick requested changes

2024-08-05 22:48 UTC, SariGlick commented on client-side/test/loader/loader.test.js
> +import { render, screen } from '@testing-library/react';
please add stories folder

2024-08-06 11:20 UTC, merged