Connecting of browsing data and website blocking
SariGlick/TimeOut pull request #110
Opened 2024-07-30 10:34 UTC by Ruthgoshen2004

I've uploaded it to this branch instead of my branch, since that's where I dropped the code because the changes would have required starting to rewrite everything

2024-07-31 06:23 UTC, Ruth708090 reviewed
Clear, readable and organized code.

2024-07-31 23:09 UTC, SariGlick requested changes

2024-07-31 23:09 UTC, SariGlick commented on extension-ui/background.js
> +  await updateTimeForPreviousTab();
part of the code in onActivated and onUpdated is same, please use common function

2024-08-03 23:59 UTC, SariGlick approved these changes

2024-08-08 09:31 UTC, Ruth708090 approved these changes

2024-08-08 09:53 UTC, merged