did all changes
SariGlick/TimeOut pull request #114
Opened 2024-07-31 09:45 UTC by MalkySinowitz

opened new branch

2024-07-31 09:52 UTC, batiFinkelshtein approved these changes
this is excelent code!!!

2024-08-06 07:14 UTC, SariGlick commented on extension-ui/manifest.json
> +    "48": "images/icon48.png"
where is this file?

2024-08-06 07:41 UTC, batiFinkelshtein approved these changes
looks complete!

2024-08-06 18:43 UTC, e171271 requested changes

2024-08-06 18:43 UTC, e171271 commented on extension-ui/background.js
> +    priority: 2
why the priority and icons are constants? maybe we will want to customize them

2024-08-07 07:06 UTC, batiFinkelshtein approved these changes
the mistakes are fixed

2024-08-07 17:01 UTC, EA171 approved these changes

2024-08-07 17:01 UTC, e171271 approved these changes

2024-08-07 17:01 UTC, merged