Report page
SariGlick/TimeOut pull request #116
Opened 2024-08-01 07:44 UTC by ruth4453

2024-08-01 07:58 UTC, ayeletBinder approved these changes

2024-08-04 23:10 UTC, SariGlick requested changes

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.jsx
> +      headers: ['id', 'website_name', 'total_time', 'avg_for_day'],
please replace with readable titles, for example "Website Name" instead of "website_name"
move titles to constants file

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.jsx
> +      <h1 className="title">select the time arrange for your report</h1>
move all texts to constants file

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.jsx
> +        {dateTimePiker &&
replace with selectedOption.value check

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.jsx
> +        <Select onChange={(selectedValue) => selectFunction(selectedValue)} className="primary" options={OPTION_ARRAY} title="time arrange" size='medium' widthOfSelect="150px" />
declare width with %

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.jsx
> +        {data[0] && <PdfGenerator data={data} />}
add download as excel button

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.scss
> +    margin-bottom: 100px;
replace with %

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.scss
> +    background-color: white;
save all colors in variables

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/Report/report.scss
> +    color: black !important;
dont use important, find another way

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/components/profileComponent.jsx
> +  return (
why do you need this component?
If it's unnecessary remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/index.js
> -import './index.scss';
remove changes from this file

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/auth/auth.selector.js
> + * @typedef {Object} RootState
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/auth/auth.slice.js
> +import { AuthUser } from "../../types/types.js";
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/preference/preference.selector.js
> + * @typedef {Object} RootState
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/preference/preference.slice.js
> +/**
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/profile/profile.selector.js
> + * @typedef {Object} ProfileStateType
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/profile/profile.slice.js
> +
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/store.jsx
> +import { useSelector } from 'react-redux';
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/user/user.selector.js
> + * @property {UserStateType} user
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/user/user.slice.js
> +import { User } from '../../types/types';
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.selector.js
> +/**
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.slice.js
> +
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/router/layout.jsx
> +import { Outlet } from "react-router-dom";
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/router/router.jsx
> +import {createBrowserRouter } from "react-router-dom";
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/services/profileService.js
> +    try {
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/services/websiteService.js
> +    try {
Is this change is yours?
If not, remove it

2024-08-04 23:10 UTC, SariGlick commented on client-side/src/stories/Button/GenericButton.css
> +  background-color: black;
save all colors in variables

2024-08-11 21:48 UTC, SariGlick approved these changes

2024-09-08 22:14 UTC, SariGlick approved these changes

2024-09-10 20:21 UTC, e171271 approved these changes

2024-09-10 20:21 UTC, merged