login-fix and add redux and i am not a robot
SariGlick/TimeOut pull request #117
Opened 2024-08-01 12:15 UTC by Chani-Pielet

ביקשתם שכל הגדלים יהיו באחוזים, תיקנתי את מה שהיה אפשרי. 
היה כמה מקומות שלא ניתן להשתמש ב%

2024-08-01 12:36 UTC, estush approved these changes

2024-08-03 23:30 UTC, SariGlick requested changes

2024-08-03 23:30 UTC, SariGlick commented on client-side/.env
> +REACT_APP_SECRET_CODE_CAPVAL='6Ld5uBoqAAAAAKwPXqo5eanm9ZFSuOoBBSdl00pE'
Is this value should be constant for all users?

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/Login.jsx
> +  email: Yup.string().email('Invalid email format').required('Email is required'),
please move all texts to constants file, and use them

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/Login.jsx
> +function Login({ apiUrl = 'http://localhost:5004' }) {
please save URL in .env file

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/Login.jsx
> +  const [capVal, setCapVal] = useState(null);
rename to understandable name

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +  max-width: 400px;
replace with %

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +    height: 50px;
replace with %

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +    margin-top: 10px;
replace with %

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +    margin-left: 100px;
replace with %

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +    margin-bottom: 14%;
replace with %

2024-08-03 23:30 UTC, SariGlick commented on client-side/src/login/login.scss
> +@media (max-width: 568px) {
replace with %

2024-08-04 19:06 UTC, SariGlick requested changes

2024-08-04 19:06 UTC, SariGlick commented on client-side/src/App.jsx
> +        {/* <Footer /> */}
why do you comment the footer?

2024-08-06 17:58 UTC, e171271 approved these changes

2024-08-06 19:52 UTC, SariGlick approved these changes

2024-08-07 16:36 UTC, EA171 approved these changes

2024-08-07 16:36 UTC, merged