Shoshi/profile page
SariGlick/TimeOut pull request #124
Opened 2024-08-04 10:17 UTC by Shoshana-Yudelevitz

עשיתי את המשימה add pagination for profiles table, display "מספר שמתקבל" profiles for a page
בעמוד   TableComponent שמתאימה לכל מספר שיתקבל, ומוגדרת כברירת מחדל.
ועדכנתי את העמוד ProfilePageComponent שישלח את המספר 5 כמו שביקשו במשימה.

2024-08-04 10:20 UTC, avishag-gvili approved these changes

2024-08-07 17:32 UTC, e171271 requested changes
I review for step 1, after you will fix all I'll move over the code again

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +import ToastMessage from '../../stories/Toast/ToastMessage.jsx';
please re-order the imports

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +  const [errorText, setErrorText] = React.useState('');
please import useState in the react import line and use it here

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +  const handleClose = useCallback(() => {
why do you need useCallback? - relevant for all functions

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +    <React.Fragment>
why do you need fragment?

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +              width='100%'
why do you have styles here? it should be in scss file

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +          {(!data.name || data.name.length < 2 || data.name.length > 50 || !data.status) ? (
please create a variable for this condition and use it here

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/addProfileComponent.jsx
> +                <Button color="success" type="submit" disabled={!data.name || data.name.length < 2 || data.name.length > 50 || !data.status}>
please create a variable for this condition and use it here

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profileActivationComponent.jsx
> +const ProfileActivationTimer = ({ profileActivationTime }) => {
please add default value

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profileActivationComponent.jsx
> +        <div className="timer-label">Time Left</div>
please move text to constants file

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profileActivationComponent.jsx
> +export default ProfileActivationTimer;
please add prop-ytpe

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profileActivationComponent.jsx
> +        trailColor="#d6d6d6"
move all styles to scss file

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profilePageComponent.jsx
> +import '../../styles/profilePageStyle.scss';
please re-order the imports

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profilePageComponent.jsx
> +const ProfilePageComponent = ({ userId }) => {
please add default value

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profilePageComponent.jsx
> +      await updateProfileApi(selectedProfile._id, profileToUpdate);
maybe you can join the both server calls to one,for decrease time?

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profilePageComponent.jsx
> +      dispatch(updateProfile(profileToUpdate));
you should dispatch only if the server call succeed

2024-08-07 17:32 UTC, e171271 commented on client-side/src/components/profileComponents/profilePageComponent.jsx
> +    if (editedRows.id==='new'&&(isWebsiteInProfile(editedRows.url, selectedProfile))) {
please change all the if else to switch case

2024-08-07 17:32 UTC, e171271 commented on client-side/src/router/router.jsx
> +
don't use hard-code values

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/stylies.scss
> +@import url('https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap');
please move all variables to variables file, this stiles file already deleted from main branch

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +import GenericButton from '../Button/GenericButton.jsx';
please join all mui imports to one

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +  pageSize
please add default values to each one that not marked as required

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +        if (header === 'status') {
please change to switch case

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +            <Tooltip title='This field is optional'>
please move text to constants file - do it in all your code

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +      headerName: 'Actions',
what is the difference between this and what you have in line 70 - 83, are they the same?

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +    <div className="table" style={{ width: widthOfTable, marginTop: "8%" }}>
move all styles to scss file - do it in all your code

2024-08-07 17:32 UTC, e171271 commented on client-side/src/stories/table/TableComponent.jsx
> +TableComponent.defaultProps = {
please remove defaultProps and add default values instead

2024-08-07 17:32 UTC, e171271 commented on client-side/src/styles/profileActivationTimer.scss
> +//   trail-color: $standardInfoColor; // Use standard info color for trail
please remove comments

2024-08-07 17:32 UTC, e171271 commented on client-side/src/styles/profileActivationTimer.scss
> +.timer-wrapper {
this file is looks like css file, scss file should have hierarchy.

2024-08-07 17:32 UTC, e171271 commented on client-side/src/styles/profilePageStyle.scss
> +
this file is looks like css file, scss file should have hierarchy.

2024-08-07 17:32 UTC, e171271 commented on client-side/src/styles/profilePageStyle.scss
> +  color:  rgb(103, 252, 210) ;
please move all colors and fonts to variables

2024-08-07 17:32 UTC, e171271 commented on server-side/controllers/profile.controller.js
> +        const profiles = await Profile.find();
you shouldn't fetch from the collection from the collection, you should do it from service file - do it in all your code

2024-08-11 07:35 UTC, closed without merging