Batiallowed sites
SariGlick/TimeOut pull request #125
Opened 2024-08-04 10:22 UTC by batiFinkelshtein

i add white list for the allwed sites

2024-08-04 10:34 UTC, MalkySinowitz approved these changes
looks great!

2024-08-04 23:24 UTC, SariGlick requested changes

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/background.js
> +  chrome.storage.local.get(["blockedSites", "allowedSites", "isBlackList"], (data) => {
allowed sites aren't stored in local storage, they are saved in DB
please remove it
you can declare a list in variable for developing time, until we'll get the data from the server

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/background.js
> +      if (allowedSitesCache.some(site => hostname.includes(site))) {
check only  if (!allowedSitesCache.some(site => hostname.includes(site))) without the return;

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/background.js
> +          console.log(`Added to blocked sites: ${hostname}`);
remove console logs

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/background.js
> +    const hostname = request.hostname.toLowerCase();
you can't add in extension allowed site, it comes only from profile in DB

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/background.js
> +    ensureCachesInitialized(() => {
you can't toggle the mode, it's up to the profile's status you got from DB

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.js
> +  allowedSitesBtn.addEventListener('click', function () {
we dont have tab of white list

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  padding: 20px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  width: 300px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  background-color: #007BFF;
save all colors to variables

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  padding: 10px 15px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  margin: 5px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  margin: 20px 0;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  padding: 8px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  margin: 5px 0;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  padding: 10px;
replace with %

2024-08-04 23:24 UTC, SariGlick commented on extension-ui/popup.scss
> +  margin: 5px 0;
replace with %

2024-08-05 10:44 UTC, MalkySinowitz approved these changes
looks good

2024-08-11 13:50 UTC, MalkySinowitz approved these changes
great!

2024-08-11 21:50 UTC, SariGlick approved these changes

2024-08-11 21:50 UTC, merged