malky/active profile
SariGlick/TimeOut pull request #126
Opened 2024-08-04 13:54 UTC by MalkySinowitz

on tab opened, get the user's settings from the DB and save them in local storage

2024-08-05 07:28 UTC, batiFinkelshtein approved these changes
this changes looks good

2024-08-06 19:08 UTC, e171271 requested changes

2024-08-06 19:08 UTC, e171271 commented on extension-ui/background.js
> +  const userId = 'm123';
userId shouldn't be hard-code

2024-08-06 19:08 UTC, e171271 commented on extension-ui/background.js
> +  fetch(`http://localhost:3000/api/settings/${userId}`)
move the basic url to variable

2024-08-07 07:18 UTC, batiFinkelshtein approved these changes
fix!

2024-08-07 07:35 UTC, batiFinkelshtein approved these changes

2024-08-07 17:33 UTC, e171271 approved these changes

2024-08-11 14:29 UTC, e171271 approved these changes

2024-08-11 14:30 UTC, merged