Shoshi/home page
SariGlick/TimeOut pull request #135
Opened 2024-08-05 15:37 UTC by Shoshana-Yudelevitz

הוספתי קומפוננטה של עמוד בית -homePageComponent
הוספתי לזה עמוד עיצוב -homePage בתיקית STYLES

2024-08-05 15:40 UTC, dvory-git approved these changes

2024-08-07 17:36 UTC, e171271 requested changes

2024-08-07 17:36 UTC, e171271 commented on client-side/src/components/homeComponent/homePageComponent.jsx
> +              <h2>Enhance Your Browsing Experience with Our Chrome Add-on</h2>
please move all texts to constants file - do it in all your code

2024-08-08 17:17 UTC, e171271 requested changes
this branch should have only changes that are connected to homePage development

2024-08-08 17:17 UTC, e171271 commented on client-side/src/axios/middleware.js
> +    console.log(url)
please remove all occurrences of console log from your code

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponent.jsx
why did you remove this component? is it a mistake or not?

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponents/ProfileActions.jsx
> +export default function ProfileActions({ handleSave, handleClose, handleDelete }) {
please add default values for each prop that not marked as required, also please add prop-type definition

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponents/ProfileActions.jsx
> +                <Button sx={{ color: ' rgb(103, 252, 210) ' }} onClick={handleClose}>
colors should be in scss file - do it in all your code

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponents/ProfileForm.jsx
> +//     );
please remove comments from all your code

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponents/ProfileForm.jsx
> +export default function ProfileForm({ formData, setFormData }) {
please add default values for each prop that not marked as required, also please add prop-type definition - do it for all components

2024-08-08 17:17 UTC, e171271 commented on client-side/src/components/profileComponents/ProfileForm.jsx
why profiles changes is related to hompePage development?

2024-08-11 07:33 UTC, closed without merging