display icons when mouse over on message
SariGlick/TimeOut pull request #136
Opened 2024-08-06 11:02 UTC by ruth4453

2024-08-06 11:26 UTC, ayeletBinder approved these changes

2024-08-06 19:28 UTC, e171271 requested changes

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +import { useState } from 'react';
please join the 2 reacts imports

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +import { Visibility, Delete, DataObject } from '@mui/icons-material';
please join all mui imports to one

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +        await axios.put(`http://localhost:5000/message/${itemId}`,newMessage)
move the basic url to variable - do it in all your code

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +            console.log(res.data)
remove all coneole log

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +        console.log("faild")
console in catch should be coneole.error - do it in all your code

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +                                <div className="icons-wrapper">
move the titles to constants files

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +                                    >
styles should be in scss file

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.jsx
> +const ListComponent = ({dataObject}) => {
please add default value

2024-08-06 19:28 UTC, e171271 commented on client-side/src/stories/list/List.scss
> +    width: 220px;
please use % instead of px
and move all colors to variables
do it in all the file

2024-09-08 22:41 UTC, SariGlick approved these changes

2024-09-09 12:36 UTC, e171271 approved these changes

2024-09-09 12:36 UTC, merged