add collections pendingUsers and invitations to database
SariGlick/TimeOut pull request #137
Opened 2024-08-06 11:36 UTC by est8906

2024-08-07 06:54 UTC, SariGlick requested changes

2024-08-07 06:54 UTC, SariGlick commented on server-side/models/invitation.model.js
> +    invitedUserID: { type: Schema.Types.ObjectId, ref: 'Users', required: true },
missing inviterID.
notice that invitedUserID could be user or pendingUser... think about solutions

2024-08-07 06:54 UTC, SariGlick commented on server-side/models/pendingUser.model.js
> +    userID: { type: Schema.Types.ObjectId, ref: 'Users', required: true },
userId is not taken from users, it doesn't exist there

2024-08-14 18:02 UTC, e171271 requested changes

2024-08-20 13:13 UTC, e171271 commented on server-side/controllers/invitation.controler.js
> +        const invitations = await Invitations.find().select('-__v');
1. done as well
2. you still need to add return statements to all

2024-09-01 09:35 UTC, e171271 approved these changes

2024-09-01 09:49 UTC, SariGlick approved these changes

2024-09-01 11:06 UTC, EA171 approved these changes

2024-09-01 11:19 UTC, EA171 approved these changes

2024-09-01 11:24 UTC, merged