add manifest file to extension-ui
SariGlick/TimeOut pull request #14
Opened 2024-07-09 12:24 UTC by est8906

it is excelent

2024-07-16 11:39 UTC, Ruth708090 approved these changes
ב"ה הקוד נראה מעולה קריא ונהיר!

2024-07-17 15:56 UTC, EA171 requested changes

2024-07-17 15:56 UTC, EA171 commented on extension-ui/background.js
> +            window.location.href = chrome.runtime.getURL('hoops.html');
please add TODO comment - to remember add UI for the oops window

2024-07-17 15:56 UTC, EA171 commented on extension-ui/content.js
> +    console.log({blockedSites});
remove console.log

2024-07-17 15:56 UTC, EA171 commented on extension-ui/hoops.html
> +  <style>
please move the styles to separate file

2024-07-17 15:56 UTC, EA171 commented on extension-ui/popup.html
> +    body {
please move styled to separate window

2024-07-17 15:56 UTC, EA171 commented on extension-ui/popup.html
> +  <div class="container">
please add TODO comment - to use generic components and style this page

2024-07-17 15:56 UTC, EA171 commented on extension-ui/popup.js
> +    // const url = new URL(inputUrl);
remove comment

2024-07-18 07:55 UTC, SariGlick requested changes

2024-07-18 07:55 UTC, SariGlick commented on extension-ui/background.js
> +  const url = new URL(details.url);
put this in try-catch for invalid URLs

2024-07-18 07:55 UTC, SariGlick commented on extension-ui/background.js
> +  chrome.storage.local.get(["blockedSites"], (data) => {
wherever you used chrome.storage.local.get, please save in to variable and use it. only if it's empty, get the data again from the local storage

2024-07-21 14:56 UTC, e171271 approved these changes
opened another sub-task for adding support for scss files

2024-07-21 14:57 UTC, EA171 approved these changes

2024-07-21 20:07 UTC, SariGlick approved these changes

2024-07-21 20:08 UTC, merged