Shoshi/home page conponent
SariGlick/TimeOut pull request #145
Opened 2024-08-11 07:21 UTC by Shoshana-Yudelevitz

שיניתי את העמוד home page conponent שלא יהיה קשור לעניין הפרופילים...

2024-08-11 07:26 UTC, MiryamGabay reviewed
home page

2024-08-11 14:59 UTC, e171271 requested changes

2024-08-11 14:59 UTC, e171271 commented on client-side/src/styles/homePage.scss
> +$white-color: #ffffff;
variables should be declared in variables file

2024-08-11 14:59 UTC, e171271 commented on client-side/src/styles/homePage.scss
> +  font-family: 'Nanum Gothic', sans-serif;
font-family should come from variables file

2024-08-11 14:59 UTC, e171271 commented on client-side/src/styles/homePage.scss
> +  min-width: 200px;
use % instead of px

2024-08-11 14:59 UTC, e171271 commented on client-side/src/styles/homePage.scss
please use scss structure, currently your file looks like css file

2024-08-14 18:19 UTC, e171271 commented on client-side/src/styles/homePage.scss
yiu should have one primary class (maybe the homePage) and all the styles should come inside

2024-09-01 12:59 UTC, EA171 requested changes

2024-09-01 12:59 UTC, EA171 commented on client-side/src/components/homePageComponent.jsx
> +// import React from 'react';
please remove all the comments

2024-09-01 12:59 UTC, EA171 commented on client-side/src/styles/homePage.scss
> +//   color: $black-color;
please remove all the comments

2024-09-01 13:22 UTC, e171271 approved these changes

2024-09-01 13:22 UTC, EA171 approved these changes

2024-09-01 13:22 UTC, merged