designed oops page
SariGlick/TimeOut pull request #152
Opened 2024-08-12 08:05 UTC by MalkySinowitz

2024-08-12 08:09 UTC, batiFinkelshtein approved these changes

2024-08-12 08:09 UTC, batiFinkelshtein commented on extension-ui/oops.scss
please change the px to%

2024-08-12 09:18 UTC, batiFinkelshtein approved these changes
the code show very good!

2024-08-15 09:36 UTC, e171271 requested changes

2024-08-15 09:36 UTC, e171271 commented on extension-ui/oops.html
> +      <p>This site is blocked according to your current profile settings in timeOut</p>
move all texts to constants file

2024-08-15 09:36 UTC, e171271 commented on extension-ui/oops.scss
> +  background-color: #f0f4f8;
the following comments relevant for all this file
1. colors and font-family should come from variables file
2. don't use px's
3. use scss structure
4. you can't write styles on elements like body, h1, p etc, you should add classes or id's and style them

2024-09-01 09:47 UTC, batiFinkelshtein approved these changes
you fix your wrongs!

2024-09-01 13:01 UTC, merged