fix
SariGlick/TimeOut pull request #156
Opened 2024-08-14 08:12 UTC by efrathartman

2024-08-14 08:18 UTC, Shoshana-Yudelevitz reviewed
efrat branch

2024-08-14 16:16 UTC, EA171 requested changes

2024-08-14 16:16 UTC, EA171 commented on client-side/src/App.jsx
> +        <SignUp/>
why you should added this to the App file?

2024-08-14 16:16 UTC, EA171 commented on client-side/src/axios/middleware.js
> +    const response = await axios.create({baseURL:url}).post(path,data,
please remove console.logs and format the file

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/PasswordStrength.jsx
> +  const PASSWORD_STRENGTH = {
this enum should be in constants file.
and the messages should be more detailed, so the user will be able to understand his mistake

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/PasswordStrength.jsx
> +  const { color, message } = strength; // הפקת צבע והודעה מקבועים
please remove comments

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/PasswordStrength.jsx
> +          height: 10,
please move styles to scss file and colors should come from variables file

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +        name: values.name,
Why are you assigning the values object to a new object? they are exactly the same

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +      localStorage.setItem("nameUser", user.name);
why you are using localStorage? use redux

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +      window.location.reload();
what is this reload?

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +      console.error("error");
please add more details about the failed

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +  const [robotPass, setRobotPass] = useState(null)
move all states declaration to be in the start of the component

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +            label="user name"
labels should be in constants file - do it for all

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +            style={{ height: '50px', marginBottom: '16px' }}
styles should be in scss file - do it for all

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +          sitekey='6Ld5uBoqAAAAAKwPXqo5eanm9ZFSuOoBBSdl00pE'
move this key to env

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.scss
> +    border: 1px solid #ccc;
colors should be in variables file

2024-08-14 16:16 UTC, EA171 commented on client-side/src/components/signUp/signUp.scss
this file is looks like css not scss

2024-08-14 16:16 UTC, EA171 commented on client-side/src/services/userService.js
> +        console.log(userData,"userdata");
remove console.logs

2024-08-14 16:16 UTC, EA171 commented on client-side/src/stories/GenericInput/genericInput.scss
> +    margin-right: 200px;
don't use px, only %

2024-08-14 16:16 UTC, EA171 commented on client-side/src/stories/header/header.jsx
> +  const [currentname, setCurrentname] = useState(localStorage.getItem('nameUser') || null);
why localStorage?

2024-08-14 16:16 UTC, EA171 commented on client-side/src/stories/header/header.jsx
> +              </IconButton>}
what is this duplication?
should the avatar be const? shouldn't it come from the user profile definition?

2024-08-20 11:36 UTC, EA171 commented on client-side/src/components/signUp/PasswordStrength.jsx
> +  const PASSWORD_STRENGTH = {
the messages has not enough details

2024-08-20 11:41 UTC, EA171 commented on client-side/src/components/signUp/signUp.scss
> +    border: 1px solid #ccc;
variables should be defined in separate variables.scss file

2024-08-20 11:49 UTC, EA171 requested changes

2024-08-20 11:49 UTC, EA171 commented on client-side/src/App.jsx
> +import SignUp from './components/signUp/signUp.jsx';
remove unused imports

2024-08-20 11:49 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +import './signUp.scss';
scss imports should be the last

2024-08-20 11:49 UTC, EA171 commented on client-side/src/components/signUp/signUp.jsx
> +      window.location.href="/home"
use useNavigate instead window.location.href="/home"

2024-09-10 19:46 UTC, EA171 approved these changes

2024-09-10 19:47 UTC, e171271 approved these changes

2024-09-10 19:47 UTC, merged