Liel/new message notifications
SariGlick/TimeOut pull request #160
Opened 2024-08-15 15:19 UTC by lielsa2023

2024-09-04 09:25 UTC, ayeletBinder approved these changes

2024-09-05 21:34 UTC, SariGlick requested changes

2024-09-05 21:34 UTC, SariGlick commented on client-side/src/stories/header/Icon.jsx
> +  const userId = '66961bef8ca0916dcbfdabc3'; //change the userId according the correct user...
remove static value, get current user from redux store

2024-09-05 21:34 UTC, SariGlick commented on client-side/src/stories/header/Icon.jsx
> +    <IconButton onClick={()=>{setOpenMesagges(!openMesagges);}} className="iconButton">
remove ;

2024-09-05 21:34 UTC, SariGlick commented on client-side/src/webSocket.js
> +      console.log('Connected to WebSocket server');
remove logs

2024-09-05 21:34 UTC, SariGlick commented on client-side/src/webSocket.js
> +      console.log('Disconnected from WebSocket server');
remove log

2024-09-05 21:34 UTC, SariGlick commented on server-side/app.js
> +app.use('/message',MessageRouter);
notice that you delete /api route, please return it

2024-09-05 21:34 UTC, SariGlick commented on server-side/controllers/message.controller.js
> +    debugger
remove debugger

2024-09-05 21:34 UTC, SariGlick commented on server-side/controllers/message.controller.js
> +     const messages = await Message.find().select('-__v');
move all DB calls to separated service file

2024-09-05 21:34 UTC, SariGlick commented on server-side/controllers/message.controller.js
> +    const message = await Message.findById(req.params.id,{__v:0}) //.populate('type').populate('userId');
remove comment

2024-09-05 21:34 UTC, SariGlick commented on server-side/router/message.router.js
> +// MessageRouter.post('/count/:id', getCountUnreadMessages);//???
remove comment

2024-09-05 21:34 UTC, SariGlick commented on server-side/webSocket.js
> +import { EventEmitter } from 'events';
reorder the imports

2024-09-05 21:34 UTC, SariGlick commented on server-side/webSocket.js
> +  console.log('Client connected');
remove all logs

2024-09-05 21:34 UTC, SariGlick commented on server-side/webSocket.js
> +    ws.userId = message.toString();
you should add switch-case to message.type,  ws can treat multiple types of messages

2024-09-10 18:36 UTC, SariGlick approved these changes

2024-09-10 18:36 UTC, merged