Liel sa/download as excel
SariGlick/TimeOut pull request #34
Opened 2024-07-12 09:46 UTC by lielsa2023

function for download as excel

2024-07-12 09:47 UTC, lielsa2023 commented
this is a function for dowload as excel

2024-07-14 15:50 UTC, e171271 requested changes

2024-07-14 15:50 UTC, e171271 commented on client-side/src/download as excl/downloadAsExcel.jsx
> +    bookType: 'xlsx',
where you are defined the name of the sheet and the name of the file?

2024-07-14 15:50 UTC, e171271 commented on client-side/src/download as excl/useDownLoadAsExcel.jsx
> +  { SiteName: 'Outlook', BrowsungTime: '15 m',Avg: '0.001' },
the data shouldn't be hard-coded it should be taken from a state variable

2024-07-14 15:57 UTC, e171271 requested changes

2024-07-14 15:57 UTC, e171271 commented on client-side/src/download as excl/downloadAsExcel.jsx
> +import * as XLSX from 'xlsx';
I don't see any change in package.json, you are using here a new libraries they should be added to package.json

2024-07-14 16:22 UTC, closed without merging