Create input
SariGlick/TimeOut pull request #37
Opened 2024-07-14 11:01 UTC by lielsa2023

create generic input

2024-07-14 15:48 UTC, e171271 requested changes

2024-07-14 15:48 UTC, e171271 commented on client-side/src/stories/genericInput.jsx
> +    onChange(newValue);
please check if onChange is exists because it's not defined as isRewuired in thepropTypes object

2024-07-14 15:48 UTC, e171271 commented on client-side/src/stories/genericInput.jsx
> +      setHelperText(validationResult.helperText || 'Invalid input');
please define the 'Invalid input' in a constant variables file and import it here

2024-07-14 15:48 UTC, e171271 commented on client-side/src/stories/genericInput.scss
> +$color-black: black;
please take the variables from stylies.scss file that includes all the variables,

2024-07-15 15:26 UTC, e171271 approved these changes

2024-07-16 06:49 UTC, SariGlick approved these changes

2024-07-16 06:50 UTC, merged