update_node
SariGlick/TimeOut pull request #52
Opened 2024-07-16 09:06 UTC by efrathartman

הוספתי פונקצית SIGNIN, את כל עניין ה   TOKEN- usermodel, auth.js
הוספתי פונקצית עדכון סיסמא -resetPasword

2024-07-16 09:08 UTC, Shoshana-Yudelevitz reviewed
NODE עדכון-

2024-07-23 15:44 UTC, EA171 commented on server-side/controllers/user.controller.js
> +let transporter = nodemailer.createTransport({
you shouldn't send an email from here, you should call to email service that Malki Sinowitz and Baty Finklshtein created, ask them about details

2024-07-23 15:44 UTC, EA171 commented on server-side/controllers/user.controller.js
> +debugger
remove all debuggers from your code

2024-07-23 15:44 UTC, EA171 commented on server-side/controllers/user.controller.js
> +  const user= "st3196420@gmail.com"
why user value is hard-code?

2024-07-23 15:45 UTC, EA171 commented on server-side/controllers/user.controller.js
> +      console.error('Error sending email:', error);
in case of error you should return the error also to the client. print it to the console is not enough

2024-07-23 15:48 UTC, EA171 commented on server-side/controllers/user.controller.js
> +    const { email, password } = req.body;
please remove console logs from all your code

2024-07-23 15:50 UTC, EA171 commented on server-side/controllers/user.controller.js
> +          return res.status(401).send({ message: 'Auth Failed' });
it's not secured to return password don't match, it should be something like: user or password doesn't exists or not match

2024-07-23 15:55 UTC, EA171 commented on server-side/middleware/auth.js
> +       const {authorization}=req.headers;
what if authorization is not existsin header?

2024-07-23 15:55 UTC, EA171 commented on server-side/middleware/auth.js
> +        next({message:err,status:401})
please add your own messsage

2024-07-23 15:56 UTC, EA171 commented on server-side/controllers/user.controller.js
> +          const token=generateToken(user);
think about saving the token in the server by cookies

2024-08-14 15:54 UTC, EA171 commented on server-side/controllers/user.controller.js
> +let transporter = nodemailer.createTransport({
why did you remove all the calls for sending emails that you had? didn't you need them already?

2024-08-14 16:05 UTC, EA171 requested changes

2024-08-14 16:05 UTC, EA171 commented on server-side/controllers/user.controller.js
> +
please remove all empty line breaks

2024-09-08 13:11 UTC, EA171 requested changes

2024-09-08 13:11 UTC, EA171 commented on server-side/controllers/user.controller.js
please move all this file and fix the following:
1. access to collections and logics should be in service file.
2. add return statements
3. add status codes

2024-09-08 13:11 UTC, EA171 commented on server-side/login.test.js
> +import { connectMongo, disconnectMongo } from '../config/db.js';
you shouldn't connect to the real DB for testing, for tests you should create mock DB and use him

2024-09-08 13:11 UTC, EA171 commented on server-side/package.json
> +  "jest": {
please check if npm test is still running in main after you added this jest block

2024-09-10 17:43 UTC, EA171 approved these changes

2024-09-10 17:59 UTC, EA171 approved these changes

2024-09-10 17:59 UTC, e171271 approved these changes

2024-09-10 17:59 UTC, merged