add redux
SariGlick/TimeOut pull request #54
Opened 2024-07-16 11:53 UTC by avishag-gvili

2024-07-16 11:54 UTC, Shoshana-Yudelevitz reviewed
הוספת REDUX לפרויקט

2024-07-17 06:30 UTC, closed without merging

2024-07-17 06:39 UTC, SariGlick requested changes

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/auth/auth.slice.ts
> +        setCurentUser: (state: AuthStateType, action: PayloadAction<AuthUser>) => {
fix curent to current

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/auth/auth.slice.ts
> +        deleteCurentUser:(state: AuthStateType) => {
fix curent to current

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/auth/auth.slice.ts
> +        updateCurentUser: (state: AuthStateType, action: PayloadAction<AuthUser>) => {
fix curent to current

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/preference/preference.slice.ts
> +        setpreferenceSlice: (state, action: PayloadAction<Preference[]>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/preference/preference.slice.ts
> +        addpreferenceSlice: (state, action: PayloadAction<Preference>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/preference/preference.slice.ts
> +        updatepreferenceSlice: (state, action: PayloadAction<Preference>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/preference/preference.slice.ts
> +        deletepreferenceSlice: (state, action: PayloadAction<string>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/profile/profile.slice.ts
> +        addprofile: (state, action: PayloadAction<Profile>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/profile/profile.slice.ts
> +        updateprofile: (state, action: PayloadAction<Profile>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/profile/profile.slice.ts
> +        deleteprofile: (state, action: PayloadAction<string>) => {
replace p with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.slice.ts
> +        setvisitedWebsite: (state, action: PayloadAction<VisitedWebsites[]>) => {
replace v with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.slice.ts
> +        addvisitedWebsite: (state, action: PayloadAction<VisitedWebsites>) => {
replace v with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.slice.ts
> +        updatevisitedWebsite: (state, action: PayloadAction<VisitedWebsites>) => {
replace v with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/redux/visitedWebsites/visitedWebsites.slice.ts
> +        deletevisitedWebsite: (state, action: PayloadAction<string>) => {
replace v with upper case

2024-07-17 06:39 UTC, SariGlick commented on client-side/src/services/profileService.ts
> +        console.log(id,"id");
remove all unnecessary console.log