add service and changes profile model
SariGlick/TimeOut pull request #58
Opened 2024-07-17 09:37 UTC by MiryamGabay

2024-07-17 09:38 UTC, avishag-gvili reviewed
הוספת service-profile

2024-07-17 11:20 UTC, SariGlick requested changes

2024-07-17 11:20 UTC, SariGlick commented on server-side/models/profile.model.js
> +                return next(new Error('In white list mode, site status cannot be "block"'));
add suitable status code

2024-07-17 11:20 UTC, SariGlick commented on server-side/models/profile.model.js
> +            if (site.status === 'block') {
missing check for open & black list

2024-07-18 06:29 UTC, avishag-gvili reviewed
הוספת profile-service

2024-09-10 19:06 UTC, merged