Avishag/add redux
SariGlick/TimeOut pull request #66
Opened 2024-07-18 12:51 UTC by avishag-gvili

2024-07-18 12:54 UTC, MiryamGabay reviewed
add redux

2024-07-18 13:03 UTC, SariGlick requested changes

2024-07-18 13:03 UTC, SariGlick commented on client-side/src/redux/store.jsx
> +import { useSelector } from 'react-redux';
move it above the local imports

2024-07-18 13:03 UTC, SariGlick commented on client-side/src/router/layout.jsx
> +import React from "react";
move it above the local imports

2024-07-18 13:12 UTC, SariGlick approved these changes

2024-07-21 07:47 UTC, Shoshana-Yudelevitz reviewed
redux אבישג

2024-07-21 08:02 UTC, SariGlick approved these changes

2024-07-21 09:41 UTC, e171271 approved these changes

2024-07-21 09:42 UTC, merged