Ayeletbinder/tabs component
SariGlick/TimeOut pull request #7
Opened 2024-07-08 19:07 UTC by ayeletBinder

i did the tabs and the header components with styles(scss), in addition i install the scss in the project.
can you allow my code?
thank you.

2024-07-09 09:28 UTC, CohenAvigail approved these changes
looks good!

2024-07-09 21:38 UTC, ayeletBinder commented
can you review again my code?
thanks!

2024-07-10 07:08 UTC, ruth4453 approved these changes

2024-07-10 09:07 UTC, e171271 commented on client-side/src/components/tabs.jsx
> +    debugger
please remove debugger

2024-07-10 09:07 UTC, e171271 commented on client-side/src/index.js
> +
please re-order the imports

2024-07-10 09:59 UTC, ayeletBinder commented on client-side/src/components/stylies/tabs.scss
> +      color: $secondary-color !important ;
עשיתי את זה רק פה כיוון שאין אפשרות לדרוס את ההגדרה הזו.

2024-07-10 11:02 UTC, e171271 requested changes

2024-07-10 11:02 UTC, e171271 commented on client-side/src/App.js
> +import './App.scss';
approved fix

2024-07-10 11:02 UTC, e171271 commented on client-side/src/components/stylies/tabs.scss
> +      color: $secondary-color !important ;
why you can't override this ?

2024-07-10 11:02 UTC, e171271 commented on client-side/src/components/tabs.jsx
> +  const [value, setValue] = React.useState(0);
approved fix

2024-07-11 08:02 UTC, e171271 approved these changes

2024-07-11 10:54 UTC, merged