Moriya / email frequency
SariGlick/TimeOut pull request #74
Opened 2024-07-21 13:02 UTC by moriya2004

### change email frequency
This PR adds functionality to update the user's email frequency preference in the Settings component. 
**Users can select from five options:**
1.  "never," 
2. "daily," 
3. "weekly,"
4.  "monthly,"
5.  "yearly." 

The selected preference is sent to the server via a PUT request, and success or error messages are displayed based on the response. Ensure the backend is configured to handle updates at the specified endpoint.

2024-07-21 13:15 UTC, BatshevaTavger approved these changes
well done

2024-07-21 16:11 UTC, EA171 requested changes

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +  'never': '🚫',
please move this enum to constants file

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +  const [emailFrequency, setEmailFrequency] = useState(Object.keys(emailFrequencyEnum)[0]);
instead of object.keys please use: emailFrequencyEnum.daily

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +      setMessage('Email frequency preference updated successfully!');
please move the message to constants file

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +      setMessage('Error updating email frequency preference. Please try again later.');
please move the message to constants file - do it for all messages

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +        title='Select Email Frequency'
title should be in constants file

2024-07-21 16:11 UTC, EA171 commented on client-side/src/components/settings/Settings.jsx
> +        label='Update User Settings'
label should be in constants file

2024-07-21 20:18 UTC, SariGlick submitted a review, later dismissed

2024-07-21 20:18 UTC, SariGlick commented on client-side/src/components/settings/Settings.jsx
> +const Settings = ({ user }) => {
.

2024-07-22 15:13 UTC, moriya2004 commented on client-side/src/components/settings/Settings.jsx
> +const Settings = ({ user }) => {
Is it ok or not?

2024-07-24 14:30 UTC, EA171 approved these changes

2024-07-24 14:31 UTC, merged