RadioButton
SariGlick/TimeOut pull request #81
Opened 2024-07-22 11:18 UTC by lielsa2023

2024-07-22 12:22 UTC, ayeletBinder approved these changes

2024-07-23 06:38 UTC, SariGlick requested changes

2024-07-23 06:38 UTC, SariGlick commented on client-side/src/stories/RadioButton/radio-Button.jsx
> +    options: PropTypes.array.isRequired,
please declare options' type more specifically, something like:
options: PropTypes.arrayOf(
    PropTypes.shape({
        value: PropTypes.string.isRequired,
        label: PropTypes.string.isRequired,
    })
).isRequired,

2024-07-23 06:38 UTC, SariGlick commented on client-side/src/stories/RadioButton/radio-Button.jsx
> +const RadioButton = ({ options, selectedOption, onChange }) => {
you should use memo, because the radio buttons are rendered and the options aren't changed.
put all this function inside memo()

2024-07-23 06:38 UTC, SariGlick commented on client-side/src/stories/RadioButton/radio-Button.jsx
> +                        labelPlacement="start"
Why start? Isn't it cause that the text appears before the radio button?

2024-07-23 06:38 UTC, SariGlick commented on client-side/src/stories/RadioButton/radio-Button.scss
> +    padding: 20px;
please replace to %

2024-07-23 06:38 UTC, SariGlick commented on client-side/src/stories/RadioButton/radio-Button.scss
> +    margin-bottom: 10px;
please replace to %

2024-07-25 11:05 UTC, SariGlick approved these changes

2024-07-25 11:05 UTC, merged