Ayelet/load component
SariGlick/TimeOut pull request #83
Opened 2024-07-22 13:00 UTC by ayeletBinder

2024-07-23 09:44 UTC, ruth4453 approved these changes

2024-07-23 12:04 UTC, SariGlick requested changes

2024-07-23 12:04 UTC, SariGlick commented on client-side/src/stories/loader/loader.stories.js
> +import GenericInput from '../inputs/genericInput';
move import to bottom, after external imports

2024-07-23 12:05 UTC, SariGlick commented on client-side/src/stories/loader/loader.scss
> +@import '../stylies.scss';
this file name has been changed

2024-07-24 14:12 UTC, EA171 approved these changes

2024-07-24 19:59 UTC, SariGlick approved these changes

2024-07-24 19:59 UTC, merged